# -*- coding: utf-8 -*-
"""AI Stock Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-vMJmP7eP6LUzCj4GrTjwDJyLYp_P_LH
"""

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/Projects/Gen AI for Stock Analysis

import pandas as pd
import yfinance as yf
from datetime import date
import numpy as np
import matplotlib.pyplot as plt

# Load CSV File
df = pd.read_csv('stock.csv')
df.head()

"""## FX Rates

"""

# Retrieve the Exchange Rates
pair = "USDINR=X"
yf.Ticker(pair).history(period="1d")["Close"].iloc[-1]

# Function to retrieve the FX-Rate
def get_fx_rate(from_currency: str, to_currency: str = "INR") -> float:
  if from_currency == to_currency:
    return 1.0
  pair = f"{from_currency}{to_currency}=X"
  try:
    rate = yf.Ticker(pair).history(period="1d")
    return rate["Close"].iloc[-1]
  except Exception:
    return np.nan

# Test the function with USD to INR
get_fx_rate("USD", "INR")

# Cache the FX rates
fx_cache = {}
for fx in df['Currency Yahoo'].unique():
  if fx == "INR":
    fx_cache[fx] = 1.0
  else:
    fx_cache[fx] = get_fx_rate(fx)

# Display the cache
print("FX Cache", fx_cache)

"""## Retrieve price data in Local currency"""

# Retrive the price of one ticker
yf.Ticker("BTC-USD").history(period = "1d")["Close"]

# Build a function to fetch prices
def get_price_local(row) -> float:
  try:
    price_native = (
        yf.Ticker(row['Ticker']).history(period = "1d")["Close"].iloc[-1]
    )
    return price_native * fx_cache[row['Currency Yahoo']]
  except Exception:
    print(f"Error fetching {row['Ticker']}")
    return np.nan

# Apply function
df.apply(get_price_local, axis=1)

"""## Gain calculation"""

# Compute gains since the last update
df["Price Today (INR)"] = df.apply(get_price_local, axis=1)
df["Value Today (INR)"] = df["Price Today (INR)"] * df["Units"]

# Compute the Gains in INR since last update and Purchase
df["Gain since Last Update (INR)"] = df["Value Today (INR)"] - df["Value Last Update"]
df["Gain since Purchase (INR)"] = df["Value Today (INR)"] - df["Units"] * df["Purchase Price"]

# Compute the Relative gains since last update and purchase
df["Gain since Last Update (%)"] = df["Gain since Last Update (INR)"] / df["Value Last Update"] * 100
df["Gain since Purchase (%)"] = df["Gain since Purchase (INR)"] / (df["Units"] * df["Purchase Price"]) * 100

# Display
df.head()

# Compute the totals
totals = {
    "Asset": "Total",
    "Ticker": "",
    "Gain since Last Update (INR)": df["Gain since Last Update (INR)"].sum(),
    "Gain since Last Update (%)": df["Gain since Last Update (%)"].sum() / df["Value Last Update"].sum(),
    "Gain since Purchase (INR)": df["Gain since Purchase (INR)"].sum(),
    "Gain since Purchase (%)": df["Gain since Purchase (%)"].sum() / ((df["Units"] * df["Purchase Price"]).sum())
}
totals

# Columns to show
columns = ["Asset", "Ticker", "Gain since Last Update (INR)", "Gain since Last Update (%)", "Gain since Purchase (INR)", "Gain since Purchase (%)"]
report = pd.concat([df[columns], pd.DataFrame([totals])], ignore_index=True)
report

# Display report with just 2 floating cases
pd.options.display.float_format = '{:.2f}'.format
report

"""# Updates

## Update to the current portfolio
"""

# Build a loop to update the portfolio
while True:
  response = input("Do you want to update the portfolio? (y/n)").strip().lower()

  if response != "y":
    print("No updates for existing assets!")
    break

  print("\nCurrent Portfolio Assets:")
  for asset in df['Asset']:
    print(f"- {asset}")

  # Ask the user to select which asset to update
  asset_name = input("\nWhich asset was updated: ").strip()

  # Check if asset exist in our portfolio
  if asset_name not in df['Asset'].values:
    print(f"Asset '{asset_name}' not found in the portfolio. Try again")
    continue

  # Ask for the units and price
  try:
    changed_units = float(input("How many units were bought (2) /sold (-2): "))
    new_purchase_price = float(input("What was the purchase price per unit (INR): "))

    # Update units average purchase price
    idx = df[df["Asset"] == asset_name].index[0]
    old_units = df.loc[idx, "Units"]
    df.loc[idx, "Units"] = old_units + changed_units

    # Update the average purchasing price
    old_purchase_price = df.loc[idx, "Purchase Price"]
    df.loc[idx, "Purchase Price"] = (old_purchase_price * old_units + changed_units * new_purchase_price) / (old_units + changed_units)

    # Display the new purhcasing price and units to the user
    print(f"New purchasing price: {df.loc[idx, 'Purchase Price']}")
    print(f"New units: {df.loc[idx, 'Units']}")

  except Exception as e:
    print(f"Error: {e}")

"""## Updating if there were new tickers added to the Portfolio"""

# Add new assets to the portfolio
while True:
  response = input("Do you want to add new assets to the portfolio? (y/n)").strip().lower()

  if response != "y":
    print("No new assets to add!")
    break

  try:
    asset_name = input("Asset name: ").strip()
    ticker = input("Ticker: ").strip()
    currency = input("Currency Yahoo: ").strip().upper() #INR USD
    units = float(input("Units: "))
    purchase_price = float(input("Purchase Price: "))

    # Create a new row
    new_row = {
        "Asset": asset_name,
        "Ticker": ticker,
        "Currency Yahoo": currency,
        "Units": units,
        "Purchase Price": purchase_price,
        "Currency Purchase": "INR",
        "Price Last Update": np.nan,
        "Date Last Update": np.nan,
        "Value Last Update": np.nan,
        "Profit Last Update": np.nan,
    }

    # Append to the dataframe
    df = pd.concat([df, pd.DataFrame([new_row])], ignore_index=True)

  except Exception as e:
    print(f"Error: {e}")

df

"""## Export the CSV

"""

# Find the date of today
today = date.today().strftime("%Y-%m-%d")
today

# Update The columns
df["Price Last Update"] = df["Price Today (INR)"]
df["Date Last Update"] = today
df.head()

# Isolating first 10 columns
df.iloc[:, :10].to_csv(f"assets {today}.csv", index=False)

"""# Finance and Stock Analysis"""

# Build a function that retrives prices and info
def get_history(ticker, period="1y", interval="1d"):
  try:
    price_history = yf.Ticker(ticker).history(period=period, interval=interval)
    info = yf.Ticker(ticker).info
    return price_history, info
  except Exception:
    print(f"Error fetching {ticker}")
    return None

price_history, info = get_history("AMZN")

price_history

info

"""## Moving Average"""

# Compute the moving averages for the 50/100/200 days and display them
def compute_moving_averages(ticker):
  # Compute moving averages
  price_history, _ = get_history(ticker)
  price_history["MA50"] = price_history["Close"].rolling(50).mean()
  price_history["MA100"] = price_history["Close"].rolling(100).mean()
  price_history["MA200"] = price_history["Close"].rolling(200).mean()

  # Retrieve the latest price and moving averages
  latest_price = price_history["Close"].iloc[-1]
  ma50 = price_history["MA50"].iloc[-1]
  ma100 = price_history["MA100"].iloc[-1]
  ma200 = price_history["MA200"].iloc[-1]

  # Display the results
  print(f"\n{ticker} - Moving Average vs Price")
  print(f"Latest Price: {latest_price:.1f}")
  print(f"MA50: {ma50:.1f} ({'Above' if latest_price > ma50 else 'Below'})")
  print(f"MA100: {ma100:.1f} ({'Above' if latest_price > ma100 else 'Below'})")
  print(f"MA200: {ma200:.1f} ({'Above' if latest_price > ma200 else 'Below'})")

  return price_history

compute_moving_averages("AMZN")

# Build a function that plots the prices and moving averages
def plot_moving_averages(price_history, ticker):
  """
  Plot the prices and moving averages
  """
  plt.figure(figsize=(12, 4))
  plt.plot(price_history.index, price_history["Close"], label="Close Price")
  plt.plot(price_history.index, price_history["MA50"], label="MA50")
  plt.plot(price_history.index, price_history["MA100"], label="MA100")
  plt.plot(price_history.index, price_history["MA200"], label="MA200")

  # Customize the plots
  plt.title(f"{ticker} Price and Moving Averages")
  plt.xlabel("Date")
  plt.ylabel("Price")
  plt.legend()
  plt.grid(True)
  plt.show()

# Plot for all tickers in the portfolio
for ticker in df["Ticker"]:
  price_history = compute_moving_averages(ticker)
  plot_moving_averages(price_history, ticker)

"""## Volatily"""

# Build a function to compute the ticker volatility
def compute_volatility(ticker, window = 50):
  """
  Compute the volatility of a ticker
  """
  # Compute the volatility
  price_history, _ = get_history(ticker)
  returns = price_history["Close"].pct_change().dropna()
  # Compute the rolling volatility
  rolling_volatility = returns.rolling(window = 100).std() * 100 * np.sqrt(250)

  # Retrieve and Display the latest volatility
  latest_volatility = rolling_volatility.iloc[-1]
  print(f"Ticker: {ticker} - Latest Volatility: {latest_volatility:.1f}%")

  return latest_volatility



volatilities = {}
for ticker in df["Ticker"]:
    vol = compute_volatility(ticker)
    print(vol)
    if vol is not None: # Check if volatility was computed successfully
        volatilities[ticker] = vol

# Build a function to plot the volatilities as a bar chart for my portfolio
def plot_volatility():
  """
  Function that retrieves the volatitiles for all my portfolio tickers and plots them as a bar chart
  """
  # Compute the volatilities
  volatilities = {}
  for ticker in df["Ticker"]:
    vol = compute_volatility(ticker)
    if vol is not None: # Check if volatility was computed successfully
        volatilities[ticker] = vol

  # Plot them as a bar chart
  plt.figure(figsize=(10, 4))
  plt.bar(volatilities.keys(), volatilities.values(), color = "skyblue")
  plt.title("Portfolio Tickers Volatility")
  plt.xlabel("Ticker")
  plt.ylabel("Volatility (%)")
  plt.xticks(rotation=45)
  plt.grid(axis = "y", linestyle = "--", alpha = 0.6)
  plt.show()
plot_volatility()

"""## P/E Ratio"""

# Build a function to retrieve the P/% ratio for a ticker
def pe_ratio(ticker):
  """
  Retrieve the P/E ratio for a ticker
  """
  try:
    _, info = get_history(ticker)
    pe = info.get('trailingPE', np.nan)
    if np.isnan(pe):
      print(f"Warning, the ticker {ticker} has no PE Ratio (negative earnings, ETF or Crypto)")
    return pe
  except Exception:
    print(f"Error fetching {ticker}")
    return np.nan

# Display the PE ratios for our portfolio
for ticker in df["Ticker"]:
  pe = pe_ratio(ticker)
  print(f"{ticker}: {pe}")

# Build a function to plot the PE ratios
def plot_pe_ratios():
  """
  Plot the PE ratios for all tickers in the portfolio
  """
  pe_ratios = {}
  for ticker in df["Ticker"]:
    pe = pe_ratio(ticker)
    if pe > 0 :
      pe_ratios[ticker] = pe

  # Plot the ratios
  plt.figure(figsize=(10, 4))
  plt.bar(pe_ratios.keys(), pe_ratios.values(), color = "red")
  plt.title("Portfolio Tickers PE Ratio")
  plt.xlabel("Ticker")
  plt.ylabel("PE Ratio")
  plt.xticks(rotation=45)
  plt.grid(axis = "y", linestyle = "--", alpha = 0.6)
  plt.show()
plot_pe_ratios()

"""## Beta"""

# Defining a function to retrieve the Beta
def beta_values(ticker):
  """ Function that retrieves the beta of stocks, if available"""
  try:
    _, info = get_history(ticker)
    beta = info.get('beta', np.nan)
    if np.isnan(beta):
      print(f"Warning, the ticker {ticker} has no Beta")
    return beta
  except Exception:
    print(f"Error fetching the beta of {ticker}")
    return np.nan

# Retrieve and show the beta for the portfolio
for ticker in df["Ticker"]:
  beta = beta_values(ticker)
  print(f"{ticker}: {beta}")

# Build a function to plot the Betas
def plot_betas():
  """ Function that blots with a bar chart the betas
  """
  betas = {}
  for ticker in df["Ticker"]:
    beta = beta_values(ticker)
    if beta > 0 :
      betas[ticker] = beta

  # Plot the Bar chart
  plt.figure(figsize=(10, 4))
  plt.bar(betas.keys(), betas.values(), color = "green")
  plt.title("Portfolio Tickers Beta")
  plt.xlabel("Ticker")
  plt.ylabel("Beta")
  plt.xticks(rotation=45)
  plt.grid(axis = "y", linestyle = "--", alpha = 0.6)
  plt.show()
plot_betas()

"""## Sharpe Ratio"""

# Build a function to compute the Sharpe Ratio
def sharpe_ratio(ticker, risk_free_rate = 0.04):
  """
  Compute the Sharpe Ratio for a ticker
  """
  # Compute the Sharpe Ratio
  price_history, _ = get_history(ticker)

  # Compute the daily returns
  returns = price_history["Close"].pct_change().dropna()

  # Compute the annualized return
  avg_daily_return = returns.mean()
  annualized_return = avg_daily_return * 252
  volatility = returns.std() * np.sqrt(252)

  # Compute the Sharpe Ratio
  sharpe = (annualized_return - risk_free_rate) / volatility

  # Display and interpret the output
  if sharpe > 1:
    print(f"{ticker} has sharpe ratio {sharpe:.1f}, has a positive return that compensated for the volatility")
  elif sharpe > 0:
    print(f"{ticker} has sharpe ratio {sharpe:.1f}, has a positive return but with a high volality")
  else:
    print(f"{ticker} has sharpe ratio {sharpe:.1f}, has a negative return. Avoid")
  return sharpe

# Test the function with our portfolio
for ticker in df['Ticker']:
  sharpe_ratio(ticker)

"""## RSI"""

# Build a function to compute the RSI for a ticker
def rsi(ticker, window = 14):
  """ Computes the RSI for a ticker. last date only"""
  price_history, _ = get_history(ticker)

  delta = price_history["Close"].diff()

  #See how many days with gains and how many with losses
  gain = delta.where(delta > 0, 0)
  loss = -delta.where(delta < 0, 0)

  # compute the rolling average gain and loss
  avg_gain = gain.rolling(window = window).mean()
  avg_loss = loss.rolling(window = window).mean()

  # Compute the RSI
  rs = avg_gain / avg_loss
  rsi = 100 - (100 / (1 + rs))

  return rsi.iloc[-1]

# Test the function to retrieve the RSI for the portfolio
for ticker in df["Ticker"]:
  print(f"{ticker}: {rsi(ticker):.1f}")

# Build a function to visualize the RSI of each portfolio Ticker
def plot_rsi():
  """ Plot the RSI for all tickers in the portfolio"""
  rsi_values = {}
  for ticker in df["Ticker"]:
    rsi_values[ticker] = rsi(ticker)

  # Plot the RSI with a bar chart
  plt.figure(figsize=(10, 4))
  plt.bar(rsi_values.keys(), rsi_values.values(), color = "orange")
  plt.axhline(y = 30, color = "g", linestyle = "--", label = "Oversold")
  plt.axhline(y = 70, color = "r", linestyle = "--", label = "Overbought")
  plt.title("Portfolio Tickers RSI (14-day)")
  plt.xlabel("Ticker")
  plt.ylabel("RSI")
  plt.xticks(rotation=45)
  plt.grid(axis = "y", linestyle = "--", alpha = 0.6)
  plt.legend()
  plt.show()
plot_rsi()

"""## MACD Crossover"""

# Build a function to compute the MACD
def compute_macd(ticker, short_window=12, long_window=26, signal_window=9):
  """
  Compute the MACD for a ticker
  """
  price_history, _ = get_history(ticker)
  close = price_history["Close"]

  # Compute the moving averages
  short_ema = close.ewm(span=short_window, adjust=False).mean()
  long_ema = close.ewm(span=long_window, adjust=False).mean()

  # Compute the MACD and Signal Lines
  price_history['MACD'] = short_ema - long_ema
  price_history['Signal'] = price_history['MACD'].ewm(span=signal_window, adjust=False).mean()

  # Latest Crossover
  macd_val = price_history['MACD'].iloc[-1]
  signal_val = price_history['Signal'].iloc[-1]
  if macd_val > signal_val:
    status = "Bullish"
  elif macd_val < signal_val:
    status = "Bearish"
  else:
    status = "Neutral"

  # Display the results
  print(f"\n{ticker} - MACD Crossover")
  print(f"MACD: {macd_val:.1f}")
  print(f"Signal: {signal_val:.1f}")
  print(f"Status: {status}")

  return price_history

# Build a function to visualize the MACD and Signal
def plot_macd(price_history, ticker):
  """
  Plot the MACD and Signal
  """
  plt.figure(figsize=(12, 4))
  plt.plot(price_history.index, price_history['MACD'], label='MACD', color='blue')
  plt.plot(price_history.index, price_history['Signal'], label='Signal', color='red')
  plt.axhline(y=0, color='black', linestyle='--')
  plt.title(f"{ticker} MACD and Signal")
  plt.xlabel("Date")
  plt.ylabel("MACD/Signal")
  plt.legend()
  plt.grid(True)
  plt.show()

# Test the function
for ticker in df["Ticker"]:
  macd = compute_macd(ticker)
  plot_macd(macd, ticker)

"""# AI Recommendation"""

!pip install langchain_openai -q

from google.colab import userdata
OPENAI_API_KEY = userdata.get('api_key')

# Set the key in OS
import os
os.environ["OPENAI_API_KEY"] = OPENAI_API_KEY

from langchain_openai import ChatOpenAI
from IPython.display import Markdown

# Connect to the api
llm = ChatOpenAI(
    temperature=0,
    model="gpt-5.4"
)

# Define the instruction
instructions = """
You are an expert portfolio analysis and personal finances.

For every ticker:
1) Summarise the key strengths and risks based on the KPIs provides.
2) Flag Momentum Signals based on the KPIs
3) Make a final recommendations (Buy, sell, hold) with a 1-2 sentence rationale

Finish with a brief overall portfolio note.
Answer in markdown
"""

# Aggregate the data
agg = {
    "Ticker": df["Ticker"].tolist(),
    "Asset": df["Asset"].tolist(),
    "Price Today": df["Price Today (INR)"].tolist(),

    # Moving Averages
    "MA50": [get_history(t)[0]['Close'].rolling(50).mean().iloc[-1] for t in df["Ticker"]],
    "MA100": [get_history(t)[0]['Close'].rolling(100).mean().iloc[-1] for t in df["Ticker"]],
    "MA200": [get_history(t)[0]['Close'].rolling(200).mean().iloc[-1] for t in df["Ticker"]],

    # Remaining KPIs
    "Volatility": [compute_volatility(t) for t in df["Ticker"]],
    "PE Ratio": [pe_ratio(t) for t in df["Ticker"]],
    "Beta": [beta_values(t) for t in df["Ticker"]],
    "Sharpe Ratio": [sharpe_ratio(t) for t in df["Ticker"]],
    "RSI": [rsi(t) for t in df["Ticker"]],
    "MACD": [compute_macd(t)["MACD"].iloc[-1] for t in df["Ticker"]],
    "Signal": [compute_macd(t)["Signal"].iloc[-1] for t in df["Ticker"]]
}

# Transform to a Pandas Dataframe
data = pd.DataFrame(agg)

messages = [
    ("system", instructions),
    ("human", data.to_string())
]

# Calling the llm
ai_recommendations = llm.invoke(messages)

# Display the message to the user
Markdown(ai_recommendations.content)

"""# Possible Investments"""

# ask the user for Tickers
new_tickers = input("Please enter new tickers separated by commas: ")
new_tickers_list =new_tickers.split(",")

# Remove empty spaced from list
new_tickers_list = [ticker.strip() for ticker in new_tickers_list]
new_tickers_list

[get_history(t)[1]["longName"] for t in new_tickers_list]

# Build a new dataframe with all the data
agg_new_tickers = {
    "Ticker": new_tickers_list,
    "Asset": [get_history(t)[1]["longName"] for t in new_tickers_list],
    "Price Today": [get_history(t)[0]["Close"].iloc[-1] for t in new_tickers_list],

    # Moving averages
    "MA50": [get_history(t)[0]['Close'].rolling(50).mean().iloc[-1] for t in new_tickers_list],
    "MA100": [get_history(t)[0]['Close'].rolling(100).mean().iloc[-1] for t in new_tickers_list],
    "MA200": [get_history(t)[0]['Close'].rolling(200).mean().iloc[-1] for t in new_tickers_list],

    # Remaining KPIs
    "Volatility": [compute_volatility(t) for t in new_tickers_list],
    "PE Ratio": [pe_ratio(t) for t in new_tickers_list],
    "Beta": [beta_values(t) for t in new_tickers_list],
    "Sharpe Ratio": [sharpe_ratio(t) for t in new_tickers_list],
    "RSI": [rsi(t) for t in new_tickers_list],
    "MACD": [compute_macd(t)["MACD"].iloc[-1] for t in new_tickers_list],
    "Signal": [compute_macd(t)["Signal"].iloc[-1] for t in new_tickers_list]
}
agg_new_tickers

# Transform into a df
df_new_tickers = pd.DataFrame(agg_new_tickers)
df_new_tickers

# Tailor the human instructions
human_instructions = f"""
This is my current portfolio: {data.to_string()}
And these are the financial instruments I am considering: {df_new_tickers.to_string()}
Assess these new instruments based on my current portfolio and provide recommendations.
"""

# Setup the messages
messages = [
    ("system", instructions),
    ("human", human_instructions)
]

# Calling the LLM
ai_recommendation = llm.invoke(messages)

# Display the message to the user
Markdown(ai_recommendation.content)

